POSSIBLE_PROBLEMS_METADATA = [
    "itching",
    "skin_rash",
    "nodal_skin_eruptions",
    "continuous_sneezing",
    "shivering",
    "chills",
    "joint_pain",
    "stomach_pain",
    "acidity",
    "ulcers_on_tongue",
    "muscle_wasting",
    "vomiting",
    "burning_micturition",
    "spotting_ urination",
    "fatigue",
    "weight_gain",
    "anxiety",
    "cold_hands_and_feets",
    "mood_swings",
    "weight_loss",
    "restlessness",
    "lethargy",
    "patches_in_throat",
    "irregular_sugar_level",
    "cough",
    "high_fever",
    "sunken_eyes",
    "breathlessness",
    "sweating",
    "dehydration",
    "indigestion",
    "headache",
    "yellowish_skin",
    "dark_urine",
    "nausea",
    "loss_of_appetite",
    "pain_behind_the_eyes",
    "back_pain",
    "constipation",
    "abdominal_pain",
    "diarrhoea",
    "mild_fever",
    "yellow_urine",
    "yellowing_of_eyes",
    "acute_liver_failure",
    "fluid_overload",
    "swelling_of_stomach",
    "swelled_lymph_nodes",
    "malaise",
    "blurred_and_distorted_vision",
    "phlegm",
    "throat_irritation",
    "redness_of_eyes",
    "sinus_pressure",
    "runny_nose",
    "congestion",
    "chest_pain",
    "weakness_in_limbs",
    "fast_heart_rate",
    "pain_during_bowel_movements",
    "pain_in_anal_region",
    "bloody_stool",
    "irritation_in_anus",
    "neck_pain",
    "dizziness",
    "cramps",
    "bruising",
    "obesity",
    "swollen_legs",
    "swollen_blood_vessels",
    "puffy_face_and_eyes",
    "enlarged_thyroid",
    "brittle_nails",
    "swollen_extremeties",
    "excessive_hunger",
    "extra_marital_contacts",
    "drying_and_tingling_lips",
    "slurred_speech",
    "knee_pain",
    "hip_joint_pain",
    "muscle_weakness",
    "stiff_neck",
    "swelling_joints",
    "movement_stiffness",
    "spinning_movements",
    "loss_of_balance",
    "unsteadiness",
    "weakness_of_one_body_side",
    "loss_of_smell",
    "bladder_discomfort",
    "foul_smell_of urine",
    "continuous_feel_of_urine",
    "passage_of_gases",
    "internal_itching",
    "toxic_look_(typhos)",
    "depression",
    "irritability",
    "muscle_pain",
    "altered_sensorium",
    "red_spots_over_body",
    "belly_pain",
    "abnormal_menstruation",
    "dischromic _patches",
    "watering_from_eyes",
    "increased_appetite",
    "polyuria",
    "family_history",
    "mucoid_sputum",
    "rusty_sputum",
    "lack_of_concentration",
    "visual_disturbances",
    "receiving_blood_transfusion",
    "receiving_unsterile_injections",
    "coma",
    "stomach_bleeding",
    "distention_of_abdomen",
    "history_of_alcohol_consumption",
    "fluid_overload.1",
    "blood_in_sputum",
    "prominent_veins_on_calf",
    "palpitations",
    "painful_walking",
    "pus_filled_pimples",
    "blackheads",
    "scurring",
    "skin_peeling",
    "silver_like_dusting",
    "small_dents_in_nails",
    "inflammatory_nails",
    "blister",
    "red_sore_around_nose",
    "yellow_crust_ooze",
]

POSSIBLE_PROBLEMS_DICT_METADATA = {
    "itching": "Itching",
    "skin_rash": "Skin Rash",
    "nodal_skin_eruptions": "Nodal Skin Eruptions",
    "continuous_sneezing": "Continuous Sneezing",
    "shivering": "Shivering",
    "chills": "Chills",
    "joint_pain": "Joint Pain",
    "stomach_pain": "Stomach Pain",
    "acidity": "Acidity",
    "ulcers_on_tongue": "Ulcers On Tongue",
    "muscle_wasting": "Muscle Wasting",
    "vomiting": "Vomiting",
    "burning_micturition": "Burning Micturition",
    "spotting_ urination": "Spotting  urination",
    "fatigue": "Fatigue",
    "weight_gain": "Weight Gain",
    "anxiety": "Anxiety",
    "cold_hands_and_feets": "Cold Hands And Feets",
    "mood_swings": "Mood Swings",
    "weight_loss": "Weight Loss",
    "restlessness": "Restlessness",
    "lethargy": "Lethargy",
    "patches_in_throat": "Patches In Throat",
    "irregular_sugar_level": "Irregular Sugar Level",
    "cough": "Cough",
    "high_fever": "High Fever",
    "sunken_eyes": "Sunken Eyes",
    "breathlessness": "Breathlessness",
    "sweating": "Sweating",
    "dehydration": "Dehydration",
    "indigestion": "Indigestion",
    "headache": "Headache",
    "yellowish_skin": "Yellowish Skin",
    "dark_urine": "Dark Urine",
    "nausea": "Nausea",
    "loss_of_appetite": "Loss Of Appetite",
    "pain_behind_the_eyes": "Pain Behind The Eyes",
    "back_pain": "Back Pain",
    "constipation": "Constipation",
    "abdominal_pain": "Abdominal Pain",
    "diarrhoea": "Diarrhoea",
    "mild_fever": "Mild Fever",
    "yellow_urine": "Yellow Urine",
    "yellowing_of_eyes": "Yellowing Of Eyes",
    "acute_liver_failure": "Acute Liver Failure",
    "fluid_overload": "Fluid Overload",
    "swelling_of_stomach": "Swelling Of Stomach",
    "swelled_lymph_nodes": "Swelled Lymph Nodes",
    "malaise": "Malaise",
    "blurred_and_distorted_vision": "Blurred And Distorted Vision",
    "phlegm": "Phlegm",
    "throat_irritation": "Throat Irritation",
    "redness_of_eyes": "Redness Of Eyes",
    "sinus_pressure": "Sinus Pressure",
    "runny_nose": "Runny Nose",
    "congestion": "Congestion",
    "chest_pain": "Chest Pain",
    "weakness_in_limbs": "Weakness In Limbs",
    "fast_heart_rate": "Fast Heart Rate",
    "pain_during_bowel_movements": "Pain During Bowel Movements",
    "pain_in_anal_region": "Pain In Anal Region",
    "bloody_stool": "Bloody Stool",
    "irritation_in_anus": "Irritation In Anus",
    "neck_pain": "Neck Pain",
    "dizziness": "Dizziness",
    "cramps": "Cramps",
    "bruising": "Bruising",
    "obesity": "Obesity",
    "swollen_legs": "Swollen Legs",
    "swollen_blood_vessels": "Swollen Blood Vessels",
    "puffy_face_and_eyes": "Puffy Face And Eyes",
    "enlarged_thyroid": "Enlarged Thyroid",
    "brittle_nails": "Brittle Nails",
    "swollen_extremeties": "Swollen Extremeties",
    "excessive_hunger": "Excessive Hunger",
    "extra_marital_contacts": "Extra Marital Contacts",
    "drying_and_tingling_lips": "Drying And Tingling Lips",
    "slurred_speech": "Slurred Speech",
    "knee_pain": "Knee Pain",
    "hip_joint_pain": "Hip Joint Pain",
    "muscle_weakness": "Muscle Weakness",
    "stiff_neck": "Stiff Neck",
    "swelling_joints": "Swelling Joints",
    "movement_stiffness": "Movement Stiffness",
    "spinning_movements": "Spinning Movements",
    "loss_of_balance": "Loss Of Balance",
    "unsteadiness": "Unsteadiness",
    "weakness_of_one_body_side": "Weakness Of One Body Side",
    "loss_of_smell": "Loss Of Smell",
    "bladder_discomfort": "Bladder Discomfort",
    "foul_smell_of urine": "Foul Smell Of urine",
    "continuous_feel_of_urine": "Continuous Feel Of Urine",
    "passage_of_gases": "Passage Of Gases",
    "internal_itching": "Internal Itching",
    "toxic_look_(typhos)": "Toxic Look (typhos)",
    "depression": "Depression",
    "irritability": "Irritability",
    "muscle_pain": "Muscle Pain",
    "altered_sensorium": "Altered Sensorium",
    "red_spots_over_body": "Red Spots Over Body",
    "belly_pain": "Belly Pain",
    "abnormal_menstruation": "Abnormal Menstruation",
    "dischromic _patches": "Dischromic  Patches",
    "watering_from_eyes": "Watering From Eyes",
    "increased_appetite": "Increased Appetite",
    "polyuria": "Polyuria",
    "family_history": "Family History",
    "mucoid_sputum": "Mucoid Sputum",
    "rusty_sputum": "Rusty Sputum",
    "lack_of_concentration": "Lack Of Concentration",
    "visual_disturbances": "Visual Disturbances",
    "receiving_blood_transfusion": "Receiving Blood Transfusion",
    "receiving_unsterile_injections": "Receiving Unsterile Injections",
    "coma": "Coma",
    "stomach_bleeding": "Stomach Bleeding",
    "distention_of_abdomen": "Distention Of Abdomen",
    "history_of_alcohol_consumption": "History Of Alcohol Consumption",
    "fluid_overload.1": "Fluid Overload.1",
    "blood_in_sputum": "Blood In Sputum",
    "prominent_veins_on_calf": "Prominent Veins On Calf",
    "palpitations": "Palpitations",
    "painful_walking": "Painful Walking",
    "pus_filled_pimples": "Pus Filled Pimples",
    "blackheads": "Blackheads",
    "scurring": "Scurring",
    "skin_peeling": "Skin Peeling",
    "silver_like_dusting": "Silver Like Dusting",
    "small_dents_in_nails": "Small Dents In Nails",
    "inflammatory_nails": "Inflammatory Nails",
    "blister": "Blister",
    "red_sore_around_nose": "Red Sore Around Nose",
    "yellow_crust_ooze": "Yellow Crust Ooze",
}
